spring:
  application:
    name: store
    host: localhost
    port: 8000
  datasource:
    url: jdbc:mysql://localhost:3306/store-exploration?createDatabaseIfNotExist=true
    username: root
    password: Charis01
stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000

paypal:
  apiUrl: https://api.paypal.com
  timeout: 1000

